- core/designsystem/src/main/java/com/hankki/core/designsystem/theme/Color.kt
- closed #7 
- color setting
- 스크린샷할게 없어서 첨부하지 않았습니다!
- color setting 완료했습니다
> [Feature/#7] color setting

- app/build.gradle.kts
- app/src/main/AndroidManifest.xml
- build-logic/src/main/java/com/hankki/build_logic/KotlinAndroid.kt
- build-logic/src/main/java/hankki.kotlin.library.gradle.kts
- build.gradle.kts
- feature/home/build.gradle.kts
- feature/home/src/main/AndroidManifest.xml
- feature/home/src/main/java/com/hankki/feature/home/HomeRoute.kt
- feature/home/src/main/java/com/hankki/feature/home/navigation/HomeNavigation.kt
- feature/main/src/main/AndroidManifest.xml
- feature/main/src/main/java/com/hankki/feature/main/MainActivity.kt
- feature/main/src/main/java/com/hankki/feature/main/MainNavigator.kt
- feature/main/src/main/java/com/hankki/feature/main/MainScreen.kt
- feature/my/src/main/java/com/hankki/feature/my/MyRoute.kt
- feature/my/src/main/java/com/hankki/feature/my/navigation/MyNavigation.kt
- feature/report/src/main/java/com/hankki/feature/report/ReportRoute.kt
- feature/report/src/main/java/com/hankki/feature/report/navigation/ReportNavigation.kt
- gradle/libs.versions.toml
- settings.gradle.kts
- closed #6 
- 네이버 지도 연결
- 내 위치 이동 구현
- permission
- 자잘한 코드 수정
https://github.com/Team-Hankki/hankki-android/assets/52882799/231668cf-3861-4b59-8043-8413a76ddfdd
- 네이버지도 연결했습니다~
- compose는 정식지원을 안해서 라이브러리 쓰느라 고생좀 했네요 ㅋㅋ
- 지금은 일단 넣어뒀고, 추후 완전히 분리해서 따로 모듈 만들고 싶은데 그건 나중에 해볼게용
- 어 이슈번호가 왜저러죠? 혜음이 도와주러 출장갔다와서 수정 안했네요 ㅋㅋ 실수~
> [Feature/#6] naver map

- app/build.gradle.kts
- app/src/main/java/com/hankki/hankkijogbo/App.kt
- build-logic/src/main/java/hankki.android.data.gradle.kts
- build-logic/src/main/java/hankki.android.feature.gradle.kts
- core/network/build.gradle.kts
- core/network/src/main/java/com/hankki/core/network/NetworkModule.kt
- core/network/src/main/java/com/hankki/core/network/StringExt.kt
- feature/home/src/main/java/com/hankki/feature/home/HomeRoute.kt
- closed #13 
- 모듈간 의존성 개선
- 없음
- 디펜던시가 맘에 안들어서 좀 수정했습니다~
> [Feature/#13] restructuring

- core/designsystem/src/main/java/com/hankki/core/designsystem/theme/Color.kt
- core/designsystem/src/main/java/com/hankki/core/designsystem/theme/Type.kt
- closed #21 
-  피그마에 추가된 폰트 추가
- 컬러 네이밍 수정
코드만 추가,수정한 것이라서 스크린샷은 찍지 않았습니다!
- 폰트 body5 추가했습니다
- 주요색상 네이밍이 변경되어 수정하였습니다
- 라벨 feature랑 add 고민하다가... add로 골랐습니다 허허
> [Feature/#21] correction design system

- core/common/src/main/java/com/hankki/core/common/extension/Modifier.kt
- closed #27 
- Bounce Click 구현
- Pressed Color 구현
<video src="https://github.com/Team-Hankki/hankki-android/assets/52882799/19008fdf-b0d7-4211-930a-eb2b280f83e3" width=270 />
- 버튼 클릭시 버튼이 작아지면서 회색(검정) 표시가 날 수 있도록 Modifier 만들었습니다.
- `scaleDown`을 활용해서 얼마나 크기가 작아질지 컨트롤 가능합니다.
- `onClick` 내부에 평소에 하던 onClick 내부 매서드 넣으시면 됩니다.
> [Feature/#27] bounce click

- core/designsystem/src/main/java/com/hankki/core/designsystem/theme/Type.kt
- closed #30 
- 폰트 추가
- 없음 
- 없음
> [Feature#30] add font

- domain/my/src/main/java/com/hankki/domain/my/entity/StoreEntity.kt
- feature/main/src/main/java/com/hankki/feature/main/MainNavigator.kt
- feature/my/src/main/java/com/hankki/feature/my/mystore/MyStoreRoute.kt
- feature/my/src/main/java/com/hankki/feature/my/mystore/MyStoreState.kt
- feature/my/src/main/java/com/hankki/feature/my/mystore/MyStoreViewModel.kt
- feature/my/src/main/java/com/hankki/feature/my/mystore/model/MyStoreModel.kt
- feature/my/src/main/java/com/hankki/feature/my/navigation/MyNavigation.kt
- closed #54
- 내가 제보한 식당,좋아요 누른 식당 같은 화면 사용
- 좋아요 누른 식당 하트 선택 및 해제 가능
https://github.com/user-attachments/assets/678ab1d4-036a-4d1a-846f-7caa1d0de711
-
> [Feature/#54] my store

- core/designsystem/src/main/java/com/hankki/core/designsystem/theme/Type.kt
- closed #58 
- text line height error 해결했습니다.
Before | After 
:--: | :--: 
- 처음 본 버그여서 당황했는데 다행히 잘 해결됐네요~
> [Fix/#58] text line height error

- core/designsystem/src/main/java/com/hankki/core/designsystem/component/button/StoreNameSearchButton.kt
- data/report/src/main/java/com/hankki/data/report/datasource/ReportDataSource.kt
- data/report/src/main/java/com/hankki/data/report/datasourceimpl/ReportDataSourceImpl.kt
- data/report/src/main/java/com/hankki/data/report/dto/response/CountResponseDto.kt
- data/report/src/main/java/com/hankki/data/report/dto/response/LocationsResponseDto.kt
- data/report/src/main/java/com/hankki/data/report/repositoryimpl/ReportRepositoryImpl.kt
- data/report/src/main/java/com/hankki/data/report/service/ReportService.kt
- domain/report/src/main/java/com/hankki/domain/report/entity/CountEntity.kt
- domain/report/src/main/java/com/hankki/domain/report/repository/ReportRepository.kt
- feature/report/src/main/java/com/hankki/feature/report/main/ReportRoute.kt
- feature/report/src/main/java/com/hankki/feature/report/main/ReportViewModel.kt
- feature/report/src/main/java/com/hankki/feature/report/navigation/ReportNavigation.kt
- feature/report/src/main/res/values/strings.xml
- settings.gradle.kts
- closed #71 
- 제보수 조회 api 연결
- 버튼 오류 수정
https://github.com/user-attachments/assets/9424b856-3d82-4a7b-bdcb-b0e9105ad2c9
- report 수 불러오는 간단한 api 붙였습니다
- 그러면서 코드도 조금 수정했어요
> [Feature/#71] report count api

- data/home/src/main/java/com/hankki/data/home/datasource/HomeDataSource.kt
- data/home/src/main/java/com/hankki/data/home/datasourcimpl/HomeDataSourceImpl.kt
- data/home/src/main/java/com/hankki/data/home/dto/response/UniversityResponseDto.kt
- data/home/src/main/java/com/hankki/data/home/repositoryImpl/HomeRepositoryImpl.kt
- data/home/src/main/java/com/hankki/data/home/service/HomeService.kt
- domain/home/src/main/java/com/hankki/domain/home/entity/response/UniversityResponseEntity.kt
- domain/home/src/main/java/com/hankki/domain/home/repository/HomeRepository.kt
- feature/home/src/main/java/com/hankki/feature/home/HomeRoute.kt
- feature/home/src/main/java/com/hankki/feature/home/HomeState.kt
- feature/home/src/main/java/com/hankki/feature/home/HomeViewModel.kt
- feature/home/src/main/java/com/hankki/feature/home/model/UniversityModel.kt
- feature/home/src/main/java/com/hankki/feature/home/navigation/HomeNavigation.kt
- feature/main/src/main/java/com/hankki/feature/main/MainScreen.kt
- closed #74 
- user University 함수 연결
- 리컴포지션 조정
https://github.com/user-attachments/assets/3a8cb3d3-dc94-4d83-b72f-be85ecf52f8b
- 구현은 완료했습니다.
- 추후 UniversitySelection 구현이 완료되면 추가 연결하도록 하겠습니다.
> [Feature/#74] get user university

- core/common/src/main/java/com/hankki/core/common/extension/Modifier.kt
- core/designsystem/src/main/java/com/hankki/core/designsystem/component/bottomsheet/HankkiStoreJogboBottomSheet.kt
- core/designsystem/src/main/java/com/hankki/core/designsystem/component/button/AddPhotoButton.kt
- core/designsystem/src/main/java/com/hankki/core/designsystem/component/button/HankkiButton.kt
- core/designsystem/src/main/java/com/hankki/core/designsystem/component/button/StoreNameSearchButton.kt
- core/designsystem/src/main/java/com/hankki/core/designsystem/component/chip/HankkiChipWithIcon.kt
- data/home/src/main/java/com/hankki/data/home/datasource/HomeDataSource.kt
- data/home/src/main/java/com/hankki/data/home/datasourcimpl/HomeDataSourceImpl.kt
- data/home/src/main/java/com/hankki/data/home/repositoryImpl/HomeRepositoryImpl.kt
- data/home/src/main/java/com/hankki/data/home/service/HomeService.kt
- domain/home/src/main/java/com/hankki/domain/home/repository/HomeRepository.kt
- feature/home/src/main/java/com/hankki/feature/home/HomeRoute.kt
- feature/home/src/main/java/com/hankki/feature/home/HomeViewModel.kt
- feature/home/src/main/java/com/hankki/feature/home/component/HankkiFilterChip.kt
- feature/report/src/main/java/com/hankki/feature/report/searchstore/SearchStoreRoute.kt
- closed #98 
- api 연결
- bounceClick 손보기
- 이미 족보에 추가된 스토어의 버튼 블러처리
https://github.com/user-attachments/assets/a294501a-3184-4bf3-9fb2-1c94af36e9b4
- api 붙였습니다
- 정욱이랑 토론해서 BounceClick 좀 수정했어요. 근데 공식이 틀린것 같아서 좀 더 손봐야 할 것 같네요...
- Radius만 고려했는데 들어가는 깊이도 고민해야하는거였어요 하하....
> [Feature/#98] add store at jogbo

- data/my/src/main/java/com/hankki/data/my/datasource/MyDataSource.kt
- data/my/src/main/java/com/hankki/data/my/datasourceimpl/MyDataSourceImpl.kt
- data/my/src/main/java/com/hankki/data/my/dto/request/NewJogboDto.kt
- data/my/src/main/java/com/hankki/data/my/repositoryimpl/MyRepositoryImpl.kt
- data/my/src/main/java/com/hankki/data/my/service/MyService.kt
- domain/my/src/main/java/com/hankki/domain/my/entity/request/NewJogboEntity.kt
- domain/my/src/main/java/com/hankki/domain/my/repository/MyRepository.kt
- feature/my/src/main/java/com/hankki/feature/my/newjogbo/NewJogboRoute.kt
- feature/my/src/main/java/com/hankki/feature/my/newjogbo/NewJogboSideEffect.kt
- feature/my/src/main/java/com/hankki/feature/my/newjogbo/NewJogboViewModel.kt
- closed #97
- 족보 생성 api 연동
- 족보 생성 성공시 sideEffect로 화면 이동
이전 화면과 동일하여 첨부하지 않았습니다
-
> [Feature/#97] create jogbo

- README.md
- closed #105 
- update
- 꾸며봤어요~
> [Docs/#105]Update README

- data/my/src/main/java/com/hankki/data/my/datasource/MyDataSource.kt
- data/my/src/main/java/com/hankki/data/my/datasourceimpl/MyDataSourceImpl.kt
- data/my/src/main/java/com/hankki/data/my/dto/response/StoreDto.kt
- data/my/src/main/java/com/hankki/data/my/repositoryimpl/MyRepositoryImpl.kt
- data/my/src/main/java/com/hankki/data/my/service/MyService.kt
- domain/my/src/main/java/com/hankki/domain/my/entity/response/StoreEntity.kt
- domain/my/src/main/java/com/hankki/domain/my/repository/MyRepository.kt
- feature/my/src/main/java/com/hankki/feature/my/mystore/MyStoreRoute.kt
- feature/my/src/main/java/com/hankki/feature/my/mystore/MyStoreViewModel.kt
- feature/my/src/main/java/com/hankki/feature/my/mystore/model/MyStoreModel.kt
- closed #108
- 좋아요 누른 식당/제보한 식당 api 연동
기존 화면과 동일하므로 첨부하지 않겠습니다
- uiState를 했는데 날아갔어요..메모장에 저장 조금씩 해놔서 일단 api연동하고 다시 수정해보겠습니다...
> [Feature/#108] user related store api

- data/my/src/main/java/com/hankki/data/my/datasource/MyDataSource.kt
- data/my/src/main/java/com/hankki/data/my/datasourceimpl/MyDataSourceImpl.kt
- data/my/src/main/java/com/hankki/data/my/dto/response/JogboDetailDto.kt
- data/my/src/main/java/com/hankki/data/my/repositoryimpl/MyRepositoryImpl.kt
- data/my/src/main/java/com/hankki/data/my/service/MyService.kt
- domain/my/src/main/java/com/hankki/domain/my/entity/response/MyJogboDetailEntity.kt
- domain/my/src/main/java/com/hankki/domain/my/repository/MyRepository.kt
- feature/main/src/main/java/com/hankki/feature/main/MainNavigator.kt
- feature/my/src/main/java/com/hankki/feature/my/component/JogboItem.kt
- feature/my/src/main/java/com/hankki/feature/my/myjogbo/MyJogboRoute.kt
- feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboDetailRoute.kt
- feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboDetailViewModel.kt
- feature/my/src/main/java/com/hankki/feature/my/navigation/MyNavigation.kt
- closed #114
- 족보 상세 보기 api 연동
이전 화면과 동일하여 첨부하지 않겠습니다
- UiState 한번에 적용하겠습니다
> [Feature/#114] jogbo detail api

- data/my/src/main/java/com/hankki/data/my/datasource/MyDataSource.kt
- data/my/src/main/java/com/hankki/data/my/datasourceimpl/MyDataSourceImpl.kt
- data/my/src/main/java/com/hankki/data/my/repositoryimpl/MyRepositoryImpl.kt
- data/my/src/main/java/com/hankki/data/my/service/MyService.kt
- domain/my/src/main/java/com/hankki/domain/my/repository/MyRepository.kt
- feature/my/src/main/java/com/hankki/feature/my/mypage/MyRoute.kt
- feature/my/src/main/java/com/hankki/feature/my/mypage/MyViewModel.kt
- feature/my/src/main/java/com/hankki/feature/my/mypage/model/MySideEffect.kt
- closed #112 
- 회원탈퇴 delete
기존과 동일합니다.
-
> [Feature/#112] delete withdraw

- data/my/src/main/java/com/hankki/data/my/datasource/MyDataSource.kt
- data/my/src/main/java/com/hankki/data/my/datasourceimpl/MyDataSourceImpl.kt
- data/my/src/main/java/com/hankki/data/my/dto/request/JogbosRequestDto.kt
- data/my/src/main/java/com/hankki/data/my/dto/response/LikedStoreResponseDto.kt
- data/my/src/main/java/com/hankki/data/my/repositoryimpl/MyRepositoryImpl.kt
- data/my/src/main/java/com/hankki/data/my/service/MyService.kt
- domain/my/src/main/java/com/hankki/domain/my/entity/response/LikedStoreResponseEntity.kt
- domain/my/src/main/java/com/hankki/domain/my/repository/MyRepository.kt
- feature/main/src/main/java/com/hankki/feature/main/MainScreen.kt
- feature/my/src/main/java/com/hankki/feature/my/component/JogboFolder.kt
- feature/my/src/main/java/com/hankki/feature/my/component/StoreItem.kt
- feature/my/src/main/java/com/hankki/feature/my/myjogbo/MyJogboRoute.kt
- feature/my/src/main/java/com/hankki/feature/my/myjogbo/MyJogboState.kt
- feature/my/src/main/java/com/hankki/feature/my/myjogbo/MyJogboViewModel.kt
- feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboDetailRoute.kt
- feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboDetailState.kt
- feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboDetailViewModel.kt
- feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboSideEffect.kt
- feature/my/src/main/java/com/hankki/feature/my/mystore/MyStoreRoute.kt
- feature/my/src/main/java/com/hankki/feature/my/mystore/MyStoreSideEffect.kt
- feature/my/src/main/java/com/hankki/feature/my/mystore/MyStoreViewModel.kt
- feature/my/src/main/java/com/hankki/feature/my/navigation/MyNavigation.kt
- feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailRoute.kt
- closed #119 
- 식당 내 족보 삭제 api 연동
이전 화면과 동일하여 첨부하지 않았습니다
- 흐엉 늦게 올려 죄송해요 ㅜ.ㅜ
> [Feature/#119] jogbo store delete api

- feature/home/src/main/java/com/hankki/feature/home/HomeRoute.kt
- feature/home/src/main/java/com/hankki/feature/home/HomeViewModel.kt
- feature/main/src/main/java/com/hankki/feature/main/MainNavigator.kt
- feature/main/src/main/java/com/hankki/feature/main/MainScreen.kt
- feature/report/src/main/java/com/hankki/feature/report/main/ReportRoute.kt
- feature/report/src/main/java/com/hankki/feature/report/main/component/SelectedImageController.kt
- feature/report/src/main/java/com/hankki/feature/report/navigation/ReportNavigation.kt
- closed #122 
- 이것
- 저것
- 디테일
- 없음
- 없음
> [Feature/#122] detail works

- core/network/src/main/java/com/hankki/core/network/OauthInterceptor.kt
- data/reissuetoken/src/main/java/com/hankki/data/reissuetoken/datasource/ReissueTokenDataSource.kt
- data/reissuetoken/src/main/java/com/hankki/data/reissuetoken/datasourceImpl/ReissueTokenDataSourceImpl.kt
- data/reissuetoken/src/main/java/com/hankki/data/reissuetoken/repositoryImpl/ReissueTokenRepositoryImpl.kt
- data/reissuetoken/src/main/java/com/hankki/data/reissuetoken/service/ReissueTokenService.kt
- domain/reissuetoken/src/main/java/com/hankki/domain/reissuetoken/repository/ReissueTokenRepository.kt
- closed #100
- 포닉스 재설정
기존과 동일합니다
- 100번째 이슈 입니다 ㅋㅋ
> [Feature #100] fix phoenix

- feature/home/src/main/java/com/hankki/feature/home/component/StoreItem.kt
> [Feature/#137] 2nd qa

- app/src/main/java/com/hankki/hankkijogbo/App.kt
- app/src/main/res/values/themes.xml
- data/home/src/main/java/com/hankki/data/home/repositoryImpl/HomeRepositoryImpl.kt
- data/report/src/main/java/com/hankki/data/report/datasourceimpl/ReportDataSourceImpl.kt
- domain/home/src/main/java/com/hankki/domain/home/entity/response/CategoriesEntity.kt
- domain/home/src/main/java/com/hankki/domain/home/entity/response/CategoryEntity.kt
- domain/home/src/main/java/com/hankki/domain/home/repository/HomeRepository.kt
- feature/home/src/main/java/com/hankki/feature/home/HomeRoute.kt
- feature/home/src/main/java/com/hankki/feature/home/HomeViewModel.kt
- feature/home/src/main/java/com/hankki/feature/home/model/UniversityModel.kt
- feature/home/src/main/java/com/hankki/feature/home/navigation/HomeNavigation.kt
- feature/main/src/main/AndroidManifest.xml
- feature/main/src/main/java/com/hankki/feature/main/MainNavigator.kt
- feature/main/src/main/java/com/hankki/feature/main/MainScreen.kt
- feature/main/src/main/java/com/hankki/feature/main/MainTab.kt
- closed #143 
- 지도 회전시 나침반 나타나는 현상 제거
- StoreItem 위치 변경
- 네이버 로고 안보이게 숨기기
- 메인화면 default value 수정
- 불필요한 서버 통신 제거
- 상단 chip 클릭 오류 해결
- 우하하~
> [Fix/143] home UI & logic

- core/common/src/main/java/com/hankki/core/common/extension/Modifier.kt
- core/common/src/main/java/com/hankki/core/common/utill/ContentUriRequestBody.kt
- feature/report/src/main/java/com/hankki/feature/report/main/ReportRoute.kt
- feature/report/src/main/java/com/hankki/feature/report/searchstore/SearchStoreRoute.kt
- feature/report/src/main/java/com/hankki/feature/report/searchstore/SearchStoreViewModel.kt
- closed #146 
- 이미지 압축 1mb로 정의
- report - 가게 이름 선택시 포커스 해제
- report - 메뉴 추가, 메뉴 클릭시 아래 여백공간 생기게 수정
- report - 메뉴 클릭된 상태로 메뉴추가 선택시 자동으로 focus 이동
https://github.com/user-attachments/assets/ca74c87f-ec89-479d-ac91-79312d349f83
https://github.com/user-attachments/assets/4a6128df-c308-47ce-b5a2-b6262246aa9b
- 수정도 좀 하고 UX도 높여봤어요~~
- 사실 디자인쌤들한테 허락 안받아서 슬쩍... 받고 승인받으면 머지할게요ㅋㅎㅋㅎㅎ
> [Fix/146] image compress error & Report Error

- feature/home/src/main/java/com/hankki/feature/home/HomeViewModel.kt
- closed #148 
- bottomSheet 올라올 때 filter가 사라지지 않는 이슈 해결
- 바보이슈~
> [Fix/#148] add clear focus

- README.md
- closed #142 
- 리드미 수정
- "로그인" 추가 ㅋㅋ
- 잘못된 링크 수정
- 레전드 이쁨. 움짤도 넣음.
> [Feature/#142] update README

- feature/my/src/main/java/com/hankki/feature/my/myjogbo/MyJogboRoute.kt
- closed #164
- 편집모드에서 시스템 뒤로가기를 누르면 편집모드 해제
- 편집모드가 아닌경우 시스템 뒤로가기를 누르면 뒤로가기 실행
-
> [Feature #164] Add back pressed event

- feature/my/src/main/java/com/hankki/feature/my/mypage/MyRoute.kt
- feature/my/src/main/java/com/hankki/feature/my/mypage/MySideEffect.kt
- feature/my/src/main/java/com/hankki/feature/my/mypage/MyViewModel.kt
- closed #170
- 기존 모달의 negative-positive 텍스트 및 이벤트를 변경했습니다
|전|후|
|:---:|:---:|
|<img src="https://github.com/user-attachments/assets/7e409df0-e9d4-4186-b73d-9b6458326a55" width=270 />|<img src="https://github.com/user-attachments/assets/844a6c52-0783-4732-a9cc-e200735648fd" width=270 />|
-
> [Fix/#170] Edit modal

- feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailRoute.kt
- closed #172
- 모달 디스크립션 텍스트 반영
- 기존과 동일합니다.
- ㅎㅎ..
> [Fix #172] store detail modal discrpition

- core/common/src/main/java/com/hankki/core/common/utill/Regex.kt
- core/designsystem/src/main/java/com/hankki/core/designsystem/component/dialog/DoubleButtonDialog.kt
- core/designsystem/src/main/java/com/hankki/core/designsystem/component/textfield/HankkiTitleTextField.kt
- feature/home/src/main/java/com/hankki/feature/home/HomeRoute.kt
- feature/home/src/main/java/com/hankki/feature/home/HomeSideEffect.kt
- feature/home/src/main/java/com/hankki/feature/home/HomeViewModel.kt
- feature/main/src/main/java/com/hankki/feature/main/MainScreen.kt
- feature/report/src/main/java/com/hankki/feature/report/finish/ReportFinishRoute.kt
- feature/report/src/main/java/com/hankki/feature/report/finish/ReportFinishState.kt
- feature/report/src/main/java/com/hankki/feature/report/finish/ReportFinishViewModel.kt
- feature/report/src/main/java/com/hankki/feature/report/finish/component/ReportFinishCard.kt
- feature/report/src/main/java/com/hankki/feature/report/main/ReportRoute.kt
- feature/report/src/main/java/com/hankki/feature/report/main/ReportSideEffect.kt
- feature/report/src/main/java/com/hankki/feature/report/main/ReportState.kt
- feature/report/src/main/java/com/hankki/feature/report/main/ReportViewModel.kt
- feature/report/src/main/res/values/strings.xml
- closed #169 
- 이슈에 있는 잡다한것들 전부다
https://github.com/user-attachments/assets/7cb12c7d-4358-4ed0-91c6-a6afed12162e
- QA시트 보고 자잘한것들 수정 했어요~
- 전부다 수정하기엔 너무 PR이 무거워질 것 같아서 이정도만 먼저 올릴게용
> [Feature/#169] 1st qa

- core/designsystem/src/main/res/drawable/img_white_gradient_top_middle.xml
- feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionRoute.kt
- feature/universityselection/src/main/java/com/hankki/feature/universityselection/component/UniversityItem.kt
- closed #199 
- 이슈 참고
- 디자인에서 준 그라디언트 세로 길이가 154여서 그대로 주었습니다.
> [Feature/#199] Update University Selection

- core/designsystem/src/main/java/com/hankki/core/designsystem/component/layout/HankkiLoadingScreen.kt
- core/designsystem/src/main/res/values/string.xml
- feature/home/src/main/java/com/hankki/feature/home/HomeRoute.kt
- feature/home/src/main/java/com/hankki/feature/home/HomeState.kt
- feature/home/src/main/java/com/hankki/feature/home/HomeViewModel.kt
- feature/report/src/main/java/com/hankki/feature/report/searchstore/SearchStoreRoute.kt
- feature/report/src/main/java/com/hankki/feature/report/searchstore/SearchStoreState.kt
- feature/report/src/main/java/com/hankki/feature/report/searchstore/SearchStoreViewModel.kt
- closed #211 
- 로딩 추가
- 로케이션에러 다이얼로그 디자인 수정
미안해요 넣기 귀찮았어요 ㅎㅎ
- 아쟈쟈~
> [Feature/#211] add loading view

- core/designsystem/src/main/java/com/hankki/core/designsystem/component/chip/HankkiCategoryChip.kt
- core/designsystem/src/main/java/com/hankki/core/designsystem/component/snackbar/HankkiSnackBar.kt
- core/designsystem/src/main/java/com/hankki/core/designsystem/component/snackbar/HankkiWhiteSnackBarWIthButton.kt
- core/designsystem/src/main/java/com/hankki/core/designsystem/component/topappbar/HankkiTopBar.kt
- data/report/src/main/java/com/hankki/data/report/dto/request/ValidateStoreRequestDto.kt
- data/report/src/main/java/com/hankki/data/report/dto/response/StoreDetailNicknameResponseDto.kt
- data/universityselection/src/main/java/com/hankki/data/universityselection/dto/request/UniversitySelectionRequestDto.kt
- domain/report/src/main/java/com/hankki/domain/report/entity/request/ValidateStoreRequestEntity.kt
- domain/report/src/main/java/com/hankki/domain/report/entity/response/UserInfoResponseEntity.kt
- feature/home/src/main/java/com/hankki/feature/home/HomeRoute.kt
- feature/home/src/main/java/com/hankki/feature/home/component/HankkiFilterChip.kt
- feature/report/src/main/java/com/hankki/feature/report/searchstore/SearchStoreViewModel.kt
- feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionRoute.kt
- closed #215 
- 아자자~
- 실시간으로 해버렸서요 ㅋ키키
> [Feature #215] fix 2nd QA

- core/designsystem/src/main/res/values/string.xml
- data/storedetail/src/main/java/com/hankki/data/storedetail/datasource/StoreDetailDataSource.kt
- data/storedetail/src/main/java/com/hankki/data/storedetail/response/StoreDetailNicknameResponseDto.kt
- domain/storedetail/src/main/java/com/hankki/domain/storedetail/entity/StoreDetailNicknameEntity.kt
- feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailRoute.kt
- feature/storedetail/src/main/res/drawable/img_gradient_frame.xml
- closed #217 
- 이슈를 참고해주세요
- 
- 그라디언트 찾아준 혜음이 감사합니다☺️
> [Feature/#217] 2nd qa

- data/home/src/main/java/com/hankki/data/home/dto/response/UniversityResponseDto.kt
- domain/home/src/main/java/com/hankki/domain/home/entity/response/UniversityResponseEntity.kt
- domain/universityselection/src/main/java/com/hankki/domain/universityselection/entity/UniversitySelectionEntity.kt
- domain/universityselection/src/main/java/com/hankki/domain/universityselection/entity/UniversitySelectionRequest.kt
- feature/home/src/main/java/com/hankki/feature/home/HomeRoute.kt
- feature/home/src/main/java/com/hankki/feature/home/HomeState.kt
- feature/home/src/main/java/com/hankki/feature/home/HomeViewModel.kt
- feature/main/src/main/java/com/hankki/feature/main/MainScreen.kt
- feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionRoute.kt
- feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionViewModel.kt
- closed #220 
- 대학 null 처리
- null 일 때 카메라 처리
https://github.com/user-attachments/assets/3dad57cd-9fd4-4606-9349-bf3b8ddbc19b
- 1, 1.5 차 QA 반영 끝~~~
> [Fix/#220] 2nd qa

- feature/home/src/main/java/com/hankki/feature/home/HomeRoute.kt
- feature/report/src/main/java/com/hankki/feature/report/main/ReportRoute.kt
- feature/report/src/main/java/com/hankki/feature/report/main/ReportState.kt
- feature/report/src/main/java/com/hankki/feature/report/main/ReportViewModel.kt
- closed #226 
- 내 족보를 새로 만들고 나서도 바텀시트가 열려있고, 데이터를 다시 패치하도록 수정
- 디폴트 줌 배율 수정
https://github.com/user-attachments/assets/6134fda0-9054-4341-b878-fe7ff9dcc058
- 아쟈자~
> [Feature/#226] add new jogbo after bottomsheet

- feature/main/src/main/java/com/hankki/feature/main/MainScreen.kt
- feature/my/src/main/java/com/hankki/feature/my/mypage/MyRoute.kt
- feature/my/src/main/java/com/hankki/feature/my/mypage/MySideEffect.kt
- feature/my/src/main/java/com/hankki/feature/my/mypage/MyState.kt
- feature/my/src/main/java/com/hankki/feature/my/mypage/MyViewModel.kt
- feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailRoute.kt
- feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionRoute.kt
- feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionState.kt
- feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionViewModel.kt
- closed #225 
- 로딩뷰 추가 및 버튼 막기
https://github.com/user-attachments/assets/a4c0a46f-92d5-4be2-ae30-aaf28f708cba
- 서버통신 플래그 문제인 줄 알았는데 레이아웃 문제일 줄이야..
> [Feature/#225]qa

- app/build.gradle.kts
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/hankki/hankkijogbo/App.kt
- core/common/build.gradle.kts
- core/common/src/main/java/com/hankki/core/common/amplitude/AmplitudeManager.kt
- core/common/src/main/java/com/hankki/core/common/amplitude/EventType.kt
- core/network/build.gradle.kts
- feature/home/src/main/java/com/hankki/feature/home/HomeRoute.kt
- feature/home/src/main/java/com/hankki/feature/home/component/StoreItem.kt
- feature/main/src/main/java/com/hankki/feature/main/MainActivity.kt
- feature/main/src/main/java/com/hankki/feature/main/MainNavigator.kt
- feature/main/src/main/java/com/hankki/feature/main/MainScreen.kt
- feature/main/src/main/java/com/hankki/feature/main/MainTab.kt
- feature/my/src/main/java/com/hankki/feature/my/myjogbo/MyJogboRoute.kt
- feature/my/src/main/java/com/hankki/feature/my/mypage/MyRoute.kt
- feature/report/src/main/java/com/hankki/feature/report/main/ReportRoute.kt
- feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailRoute.kt
- feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionRoute.kt
- feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionSideEffect.kt
- feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionViewModel.kt
- gradle/libs.versions.toml
- closed #230 
- amplitude 연결
- naver cloud Debug/Prod 구분
- Home 오류 수정
- 끝~
> [Feature/#230] amplitude

- feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionRoute.kt
- closed #232 
- 대학 선택시 null 기능 추가
- 흑흑 복구함 ㅠㅠ
> [Feature#232] rollback

- feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailRoute.kt
- closed #236 
- ! 삭제
- 꼼꼼 송혜음 선생 감사합니다.
> [Fix #236] Delete !

- feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboDetailRoute.kt
- feature/my/src/main/java/com/hankki/feature/my/mypage/MyRoute.kt
- closed #233
- 배경색 수정
- 마이페이지 탑바 고정
|전|후|
|:---:|:---:|
|<img src="https://github.com/user-attachments/assets/fea411f5-586c-451a-b684-fee0e385b85f" width=270 />|<img src="https://github.com/user-attachments/assets/4f459c73-1223-4913-9ace-c1dcbfd260e4" width=270 />|
-
> [Fix #233] Third my QA

- gradle/libs.versions.toml
- closed #240 
- "2.8.0-beta04" -> "2.8.0"
- Stable 버전이 드디어 나와서 버전업 했습니다.
- 실행상에 문제없길래 올렸습니다. 추후 문제 발견하시면 버전 다시 내리는걸 검토해야 할 것 같아요
> [Feature #240] version up navigation

- feature/home/src/main/java/com/hankki/feature/home/HomeRoute.kt
- feature/home/src/main/java/com/hankki/feature/home/HomeViewModel.kt
- closed #252 
- init -> Screen에서 호출
- 화면이 다시 그려질 때 가져와야하는데 뷰모델 생성시에만 호출해서 안되는거였어요
- 바보이슈
> [Fix #252] fix university selection error

- core/designsystem/src/main/java/com/hankki/core/designsystem/component/dialog/DoubleButtonDialog.kt
- feature/my/src/main/java/com/hankki/feature/my/mypage/MyRoute.kt
- closed #265 
- isAntiPattern 변수 추가해줘서 마이페이지 에 있는 뷰는 반대로 작동하도록 설정했습니다
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/002bd7b7-f69c-4724-8349-7bc07861c1e4" width="300" > | <video src="https://github.com/user-attachments/assets/6758d529-3995-4438-a36c-b12045fe156a" width="300" >
- 이 중요한 걸 지금 발견하다니 죄송합니다 : -(
> [Chore #265] Add isAntiPattern parameter to DoubleButtonDialog
